---
lang: en-EN
title: S9 Minimal surface solver in the rhinoceros and grasshopper software package
author: 
- Lando Schumpich 15475052
date: March 21, 2023
documentclass: report
# classoption:
#   - openleft
#   - twoside
fontsize: 12pt
---